spring:
  datasource:
    url: jdbc:mysql://localhost:3306/balanceGameV2?serverTimezone=Asia/Seoul&sendFractionalSeconds=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wkrwjs4602!
    hikari:
      maximum-pool-size: 10 # ?? ?? ?
      minimum-idle: 0 # ?? ?? ?? ?
      max-lifetime: 600000 # ?? ?? ??
#      data-source-properties:
#        useServerPrepStmts: false
#        cachePrepStmts: true # ?? ?? ?? ?? ??
#        preStmtCacheSize: 500 # ?? ?? ?? ??
#        preStmtCacheSqlLimit: 1024 # ??? ?? ??

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - jwt.yml